### ISSUE TITLE
Set up GitHub Actions

### ISSUE THREAD

**Issue by SanderOestvik** [bouvet/nord-juice-shop#11]
The following GitHub Actions are needed and need to be set up. While the exact MultiJuicer setup script is not yet ready, the setup of the actions can still be made.
- [x] Configure OpenID Connect in Azure #16 
- [x] Action for authenticating against AAD (Entra ID)
- [x] Run the AKS creation script (`manage-azure-deployment.sh`)
- [x] Run the deployment script (`manage-multijuicer.sh`) (blocked by #5 and #14)
- [ ] Run the script for ~importing the challenges to~ configuring CTFd ~(`generate-challenges.sh`)~ (`manage-ctfd.sh`) (awaits #58)

The actions should ~both~ be triggered manually ~and after a merge to the master branch.~
 
The github actions also need to be allowed to deploy resources in azure. Look into federated credentials for connecting github actions to azure.

https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-az-cli-script-of-a-specific-cli-version-via-file-present-in-your-repository
