### ISSUE TITLE
feat(ctfd): Define CTFd-Helm variables

### ISSUE THREAD

**Issue by netr0m** [bouvet/nord-juice-shop#24]
We have several ways to choose from when it comes to the deployment of the CTFd instance for our multi-juicer CTF setup. In short, the three alternatives are 
1) helm chart (as with multi-juicer itself);
2) our own setup in k8s, i.e. writing a fair amount of YAML; or
3) our own setup without k8s, e.g. Azure Container Instances

We've previously landed on going for the Helm chart, as it aligns well with our current setup, is maintained, and significantly reduces the workload incl. manual labor we'd need for the other two options. Details can be seen in the comments of issue #8.

## Tasks

Use the [bman46/CTFd-Helm](https://github.com/bman46/CTFd-Helm) helm chart
1. Override default values (config) defined in [`values.yml`](https://github.com/bman46/CTFd-Helm/blob/main/values.yaml):
    1. [x] Identify values to override (e.g. passwords, etc.)
    2. [x] Create `ctfd.yml` containing the values to override
    3. [x] Determine secret values to override using `--set`, such as `--set redis.auth.password=$REDIS_PASS`

## Example

We've made a similar approach with our multi-juicer setup:

Based on the default values defined in the multi-juicer configuration [`values.yml`](https://github.com/iteratec/multi-juicer/blob/main/helm/multi-juicer/values.yaml), we firstly identified the values we wished to override. 

Next, we created [`juicer.yml`](https://github.com/bouvet/nord-juice-shop/blob/feat/monitoring-setup-script/juicer.yaml) and proceeded to override the values from `values.yml`.

Finally, we identified the secret values we wished to override (such as passwords and other information we want to keep secret), and added them to the deployment using the `--set` flag. The task here is to identify and make a list of the variables. They will be _consumed_ in the deployment script which is part of #25 (see https://github.com/bouvet/nord-juice-shop/blob/feat/monitoring-setup-script/manage-multijuicer.sh#L119-L127 for an example with multi-juicer variables)
